-- Bloomberg TheAsia Trade Report
-- Oracle 26ai Sovereign Ledger | Stargate V16
SET LINESIZE 200;
SET PAGESIZE 100;
COLUMN STRATEGIC_DOCTRINE FORMAT A80;

SELECT 
    ASSET, 
    VALUE AS "GAIN_FCF", 
    NARRATIVE_STATUS AS "STRATEGIC_DOCTRINE"
FROM (
    SELECT ASSET, VALUE, NARRATIVE_STATUS, ORD FROM STARGATE_REPORT_2027
)
ORDER BY ORD ASC;

PROMPT *** COMMIT COMPLETE: STARGATE CLUSTER V16 SOVEREIGN ***
