-- Stargate Cluster V16: 2028 Scarcity Super-Cycle
-- Objective: BRN-WTI Spread Modeling
SET DEFINE OFF;
SET PAGESIZE 50;

SELECT 
    'BRN-WTI_2028' AS SPREAD_ID,
    ROUND(142.50 - 124.75, 2) AS PROJECTED_SPREAD,
    'CRITICAL' AS VOLATILITY_STATUS,
    'Sovereign Realignment' AS MACRO_DRIVER
FROM DUAL;

SELECT 
    ASSET AS "BIG_OIL_EIGHT",
    VALUE AS "FCF_GAIN_BN",
    NARRATIVE_STATUS AS "STRATEGIC_DOCTRINE"
FROM STARGATE_REPORT_2027
WHERE ORD >= 3;
