-- STARGATE HUB: RECTIFIED SCHEMA INSERTS
INSERT INTO market_projections (TICKER, TARGET_18M) VALUES ('NVDA', 2200.00);
INSERT INTO market_projections (TICKER, TARGET_18M) VALUES ('CITI', 95.00);
COMMIT;
